### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by nevinpuri** [rafalou38/twop#1]
I recommend one of those sand timers.

**Comment by rafalou38** [comment]
I was thinking of using this squirrel emoji from Microsoft as an original and somewhat unique logo, like the one that appears when idle
![image](https://user-images.githubusercontent.com/58974586/147750119-b4506f2e-6cd4-411b-87f2-02e7b7fe9aa3.png)



Which seems to be allowed: https://docs.microsoft.com/en-us/typography/fonts/font-faq
> **Can I make a company logo using the fonts?**
> Unless you are using an application that is specifically licensed for home, student, or non-commercial use, we do not restrict you from making logos using the Windows-supplied fonts.
> **Do these general use guidelines apply to the symbol and emoji fonts supplied with Windows?**
> Yes, they apply to all the fonts installed with Windows as system-wide resources.

Or draw one by myself.

Or maybe I should use a more basic and related logo, like an hourglass or a timer.

What do you think is best? 🤔
